--  with Ada.Text_IO; use Ada.Text_IO;
--
--  package body P_Operation.P_Withdraw is
--
--     procedure Make(Withdraw : in out T_Withdraw) is
--        Ptr_Withdraw : Ptr_Operation'Class;
--     begin
--        Ptr_Withdraw.all := Deposit;
--        Withdraw.Ptr_Account.all.Date    := Withdraw.Ptr_Account.all.Date + 1;
--
--        Withdraw.Ptr_Account.all.Balance :=
--          Withdraw.Ptr_Account.all.Balance - Withdraw.Amount;
--
--       Withdraw.Ptr_Account.all.History (Withdraw.Ptr_Account.all.Date) :=
--          Ptr_Withdraw;
--
--     end Make;
--
--     procedure Display(Withdraw : T_Withdraw) is
--     begin
--        Put_Line("Withdraw of " &T_Euro'Image (Withdraw.Amount) & " Euros");
--     end Display;
--
--  end P_Operation.P_Withdraw;
